server:
  port: 10000
  servlet:
    context-path: /back

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000000000
      max-request-size: 1000000000
  jmx:
    enabled: false
  application:
    name: back
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  profiles:
    active: dev

logging:
  level:
    cn.tourism.back.mapper: debug
